import { useState, useEffect } from 'react';
import { adminAPI } from '../services/api';
import { GitBranch, Plus, Play, Trash2, ToggleLeft, ToggleRight, RefreshCw } from 'lucide-react';

const fmt = (s: string) => s?.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()) || '';

export default function ActionChainsPage() {
  const [chains, setChains] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState({ name: '', triggerType: 'zone_state' });
  const load = async () => { try { setChains((await adminAPI.getAutoChains()).data); } catch {} finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const create = async () => { try { await adminAPI.createAutoChain({ ...form, triggerConditionJson: { state: 'critical' }, steps: [{ order: 1, actionType: 'send_push', payload: { message: 'Alert' }, delaySeconds: 0 }, { order: 2, actionType: 'set_surge', payload: { multiplier: 1.5 }, delaySeconds: 30 }] }); setShowCreate(false); load(); } catch {} };
  if (loading) return <div className="p-6 text-slate-400" data-testid="chains-loading">Загрузка...</div>;
  return (<div className="p-6 space-y-6" data-testid="action-chains-page"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-white">Action Chains</h1><p className="text-slate-400 text-sm">Многошаговые автоматические цепочки</p></div><div className="flex gap-2"><button onClick={load} className="px-3 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg text-slate-300" data-testid="refresh-chains"><RefreshCw size={16}/></button><button onClick={()=>setShowCreate(!showCreate)} className="px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white rounded-lg flex items-center gap-2" data-testid="create-chain-btn"><Plus size={16}/>Новая цепочка</button></div></div>
    {showCreate&&<div className="bg-slate-800 border border-slate-700 rounded-xl p-5 space-y-4" data-testid="create-chain-form"><h3 className="text-white font-semibold">Создать цепочку</h3><div className="grid grid-cols-2 gap-4"><input className="bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-white" placeholder="Название цепочки" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} data-testid="chain-name-input"/><select className="bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-white" value={form.triggerType} onChange={e=>setForm({...form,triggerType:e.target.value})} data-testid="chain-trigger-select"><option value="zone_state">Zone State</option><option value="incident">Incident</option><option value="provider_state">Provider State</option></select></div><div className="flex gap-2"><button onClick={create} className="px-4 py-2 bg-blue-500 text-white rounded-lg" data-testid="submit-chain-btn">Создать</button><button onClick={()=>setShowCreate(false)} className="px-4 py-2 bg-slate-700 text-slate-300 rounded-lg">Отмена</button></div></div>}
    <div className="space-y-3" data-testid="chains-list">{chains.map((ch:any)=><div key={ch.id} className="bg-slate-800 border border-slate-700 rounded-xl p-4" data-testid={`chain-${ch.id}`}><div className="flex items-center justify-between mb-3"><div className="flex items-center gap-3"><GitBranch size={18} className={ch.isEnabled?'text-blue-400':'text-slate-600'}/><div><span className="text-white font-medium">{ch.name}</span><div className="flex gap-2 mt-1"><span className="text-xs px-2 py-0.5 rounded bg-slate-700 text-slate-400">{fmt(ch.triggerType)}</span><span className="text-xs px-2 py-0.5 rounded bg-slate-700 text-slate-400">{ch.steps?.length||0} шагов</span></div></div></div><div className="flex items-center gap-2"><button onClick={()=>adminAPI.testAutoChain(ch.id).then(load)} className="p-2 hover:bg-slate-700 rounded-lg text-blue-400" data-testid={`test-chain-${ch.id}`}><Play size={16}/></button><button onClick={()=>adminAPI.toggleAutoChain(ch.id).then(load)} className={`p-2 hover:bg-slate-700 rounded-lg ${ch.isEnabled?'text-green-400':'text-slate-600'}`} data-testid={`toggle-chain-${ch.id}`}>{ch.isEnabled?<ToggleRight size={16}/>:<ToggleLeft size={16}/>}</button><button onClick={()=>adminAPI.deleteAutoChain(ch.id).then(load)} className="p-2 hover:bg-slate-700 rounded-lg text-red-400" data-testid={`del-chain-${ch.id}`}><Trash2 size={16}/></button></div></div>{ch.steps?.length>0&&<div className="flex items-center gap-2 mt-2 overflow-x-auto">{ch.steps.map((s:any,i:number)=><div key={i} className="flex items-center gap-1"><div className="bg-slate-700 rounded px-2 py-1 text-xs text-slate-300 whitespace-nowrap">{s.order}. {fmt(s.actionType)}{s.delaySeconds>0?` (+${s.delaySeconds}s)`:''}</div>{i<(ch.steps?.length||0)-1&&<span className="text-slate-600">&rarr;</span>}</div>)}</div>}<div className="grid grid-cols-3 gap-2 text-sm mt-3"><div className="bg-slate-700/50 rounded-lg p-2"><div className="text-slate-500">Выполнений</div><div className="text-white">{ch.stats?.total||0}</div></div><div className="bg-slate-700/50 rounded-lg p-2"><div className="text-slate-500">Успешных</div><div className="text-white">{ch.stats?.success||0}</div></div><div className="bg-slate-700/50 rounded-lg p-2"><div className="text-slate-500">Успешность</div><div className="text-white">{ch.stats?.successRate||0}%</div></div></div></div>)}</div></div>);
}
