import { useState, useEffect } from 'react';import { adminAPI } from '../services/api';import { RefreshCw, TrendingUp, TrendingDown, Minus } from 'lucide-react';

const fmt = (s: string) => s?.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()) || '';

export default function AutoRulePerformancePage(){const[data,setData]=useState<any[]>([]);const[loading,setLoading]=useState(true);
const load=async()=>{try{setData((await adminAPI.getAutoPerformance()).data);}catch{}finally{setLoading(false);}};
useEffect(()=>{load();},[]);
if(loading)return<div className="p-6 text-slate-400" data-testid="perf-loading">Загрузка...</div>;
const rc:Record<string,string>={keep:'bg-green-500/20 text-green-400',tune:'bg-amber-500/20 text-amber-400',disable:'bg-red-500/20 text-red-400'};
const recLabels:Record<string,string>={keep:'Оставить',tune:'Настроить',disable:'Отключить'};
return(<div className="p-6 space-y-6" data-testid="rule-performance-page"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-white">Rule Performance</h1><p className="text-slate-400 text-sm">Анализ эффективности правил</p></div><button onClick={load} className="px-3 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg text-slate-300" data-testid="refresh-perf"><RefreshCw size={16}/></button></div>
<div className="bg-slate-800 border border-slate-700 rounded-xl overflow-hidden" data-testid="perf-table"><table className="w-full text-sm"><thead><tr className="text-slate-500 border-b border-slate-700"><th className="text-left py-3 px-4">Правило</th><th className="text-left py-3 px-4">Действие</th><th className="text-right py-3 px-4">Выполн.</th><th className="text-right py-3 px-4">Успешн.</th><th className="text-right py-3 px-4">Конв.</th><th className="text-right py-3 px-4">ETA</th><th className="text-right py-3 px-4">Выручка</th><th className="text-center py-3 px-4">Статус</th><th className="text-center py-3 px-4">Рек.</th></tr></thead><tbody>{data.map((r:any)=><tr key={r.ruleId} className="border-b border-slate-700/50 text-slate-300 hover:bg-slate-750/50"><td className="py-3 px-4 text-white font-medium">{r.ruleName}</td><td className="py-3 px-4"><span className="px-2 py-0.5 rounded bg-slate-700 text-xs">{fmt(r.actionType)}</span></td><td className="text-right py-3 px-4">{r.executions}</td><td className="text-right py-3 px-4"><span className={r.successRate>70?'text-green-400':r.successRate>40?'text-amber-400':'text-red-400'}>{r.successRate}%</span></td><td className="text-right py-3 px-4"><span className={`flex items-center justify-end gap-1 ${r.avgConversionDelta>0?'text-green-400':r.avgConversionDelta<0?'text-red-400':'text-slate-500'}`}>{r.avgConversionDelta>0?<TrendingUp size={14}/>:r.avgConversionDelta<0?<TrendingDown size={14}/>:<Minus size={14}/>}{r.avgConversionDelta}</span></td><td className="text-right py-3 px-4 text-slate-400">{r.avgEtaDelta}</td><td className="text-right py-3 px-4 text-slate-400">{r.avgRevenueDelta}</td><td className="text-center py-3 px-4"><span className={`px-2 py-0.5 rounded text-xs ${r.isEnabled?'bg-green-500/20 text-green-400':'bg-slate-700 text-slate-500'}`}>{r.isEnabled?'ON':'OFF'}</span></td><td className="text-center py-3 px-4"><span className={`px-2 py-0.5 rounded text-xs font-medium ${rc[r.recommendation]||''}`}>{recLabels[r.recommendation]||r.recommendation}</span></td></tr>)}</tbody></table>{data.length===0&&<div className="text-center text-slate-500 py-8">Нет данных</div>}</div></div>);}
