import { useState } from 'react';import { adminAPI } from '../services/api';import { FlaskConical, Target } from 'lucide-react';

const fmt = (s: string) => s?.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()) || '';

export default function DryRunPage(){const[result,setResult]=useState<any>(null);const[loading,setLoading]=useState(false);const[scenario,setScenario]=useState('critical_zone_supply_drop');const[scopeType,setScopeType]=useState('zone');const[scopeId,setScopeId]=useState('kyiv-center');
const scenarios=[{v:'critical_zone_supply_drop',l:'Критическое падение предложения'},{v:'peak_hour_demand_spike',l:'Пиковый спрос'},{v:'provider_mass_offline',l:'Массовый уход мастеров'},{v:'low_conversion_zone',l:'Низкая конверсия зоны'}];
const run=async()=>{setLoading(true);try{setResult((await adminAPI.runDryRun({scenario,scopeType,scopeId})).data);}catch{}finally{setLoading(false);}};
const rc:Record<string,string>={low:'bg-green-500/20 text-green-400',medium:'bg-amber-500/20 text-amber-400',high:'bg-red-500/20 text-red-400'};
return(<div className="p-6 space-y-6" data-testid="dry-run-page"><div><h1 className="text-2xl font-bold text-white">Dry Run Simulator</h1><p className="text-slate-400 text-sm">Тестирование сценариев без реального выполнения</p></div>
<div className="bg-slate-800 border border-slate-700 rounded-xl p-5 space-y-4" data-testid="dry-run-form"><div className="grid grid-cols-3 gap-4"><div><label className="text-slate-400 text-sm block mb-1">Сценарий</label><select className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-white" value={scenario} onChange={e=>setScenario(e.target.value)} data-testid="scenario-select">{scenarios.map(s=><option key={s.v} value={s.v}>{s.l}</option>)}</select></div><div><label className="text-slate-400 text-sm block mb-1">Область</label><select className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-white" value={scopeType} onChange={e=>setScopeType(e.target.value)} data-testid="scope-select"><option value="zone">Zone</option><option value="global">Global</option></select></div><div><label className="text-slate-400 text-sm block mb-1">Scope ID</label><input className="w-full bg-slate-700 border border-slate-600 rounded-lg px-3 py-2 text-white" value={scopeId} onChange={e=>setScopeId(e.target.value)} data-testid="scope-id-input"/></div></div><button onClick={run} disabled={loading} className="px-6 py-2 bg-amber-500 hover:bg-amber-600 disabled:opacity-50 text-white rounded-lg flex items-center gap-2" data-testid="run-dry-btn"><FlaskConical size={16}/>{loading?'Выполнение...':'Запустить симуляцию'}</button></div>
{result&&<div className="bg-slate-800 border border-slate-700 rounded-xl p-5 space-y-4" data-testid="dry-run-result"><div className="flex items-center gap-3"><Target size={18} className="text-amber-400"/><span className="text-white font-semibold">Результат</span><span className={`px-3 py-1 rounded-full text-sm ${rc[result.riskLevel]||''}`}>{result.riskLevel?.toUpperCase()} RISK</span></div><div className="grid grid-cols-2 gap-4"><div><h4 className="text-slate-400 text-sm mb-2">Действия</h4><div className="space-y-1">{(result.predictedActions||[]).map((a:string,i:number)=><div key={i} className="flex items-center gap-2 bg-slate-700/50 rounded px-3 py-1.5 text-sm text-slate-300"><span className="w-5 h-5 rounded-full bg-amber-500/20 text-amber-400 text-xs flex items-center justify-center">{i+1}</span>{fmt(a)}</div>)}</div></div><div><h4 className="text-slate-400 text-sm mb-2">Влияние</h4><div className="space-y-2 text-sm">{Object.entries(result.expectedImpact||{}).map(([k,v]:any)=><div key={k} className="flex justify-between bg-slate-700/50 rounded px-3 py-1.5"><span className="text-slate-400">{k.replace('Delta','')}</span><span className={v>=0?'text-green-400':'text-red-400'}>{v>0?'+':''}{v}%</span></div>)}</div></div></div><div className="flex gap-3 text-sm text-slate-500"><span>Правил: {result.matchingRules}</span><span>Цепочек: {result.activeChains}</span></div></div>}
</div>);}
