import { useState, useEffect } from 'react';
import { adminAPI } from '../services/api';
import { Activity, Play, Pause, Square, RefreshCw, Zap } from 'lucide-react';

const fmt = (s: string) => s?.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()) || '';

export default function ExecutionMonitorPage() {
  const [data, setData] = useState<any>(null); const [loading, setLoading] = useState(true);
  const load = async () => { try { setData((await adminAPI.getAutoMonitor()).data); } catch {} finally { setLoading(false); } };
  useEffect(() => { load(); const i = setInterval(load, 3000); return () => clearInterval(i); }, []);
  if (loading) return <div className="p-6 text-slate-400" data-testid="monitor-loading">Загрузка...</div>;
  if (!data) return <div className="p-6 text-red-400">Ошибка загрузки</div>;
  const e = data.engine || {};
  const sc: Record<string,string> = { running: 'bg-green-500', stopped: 'bg-red-500', paused: 'bg-amber-500' };
  return (<div className="p-6 space-y-6" data-testid="execution-monitor-page"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-white">Execution Monitor</h1><p className="text-slate-400 text-sm">Статус движка в реальном времени</p></div><div className="flex items-center gap-2"><div className="flex items-center gap-2 bg-slate-800 border border-slate-700 rounded-lg px-3 py-2"><span className={`w-2 h-2 rounded-full ${sc[e.status]||'bg-slate-500'}`}/><span className="text-white font-medium text-sm">{e.status?.toUpperCase()}</span></div>
    {e.status==='stopped'&&<button onClick={()=>adminAPI.startAutoEngine().then(load)} className="px-3 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg flex items-center gap-1" data-testid="start-btn"><Play size={16}/>Start</button>}
    {e.status==='running'&&<button onClick={()=>adminAPI.pauseAutoEngine().then(load)} className="px-3 py-2 bg-amber-600 hover:bg-amber-700 text-white rounded-lg flex items-center gap-1" data-testid="pause-btn"><Pause size={16}/>Pause</button>}
    {e.status==='paused'&&<button onClick={()=>adminAPI.resumeAutoEngine().then(load)} className="px-3 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg flex items-center gap-1" data-testid="resume-btn"><Play size={16}/>Resume</button>}
    {e.status!=='stopped'&&<button onClick={()=>adminAPI.stopAutoEngine().then(load)} className="px-3 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg flex items-center gap-1" data-testid="stop-btn"><Square size={16}/>Stop</button>}
    <button onClick={load} className="px-3 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg text-slate-300" data-testid="refresh-monitor"><RefreshCw size={16}/></button></div></div>
    <div className="grid grid-cols-5 gap-3" data-testid="engine-stats">{[{l:'Циклов',v:e.total_cycles||0},{l:'Выполнений',v:e.total_executions||0},{l:'Успешных',v:e.successful||0},{l:'Ошибок',v:e.failed||0},{l:'Shadow',v:e.shadow_executions||0}].map(s=><div key={s.l} className="bg-slate-800 border border-slate-700 rounded-lg p-3"><div className="text-slate-500 text-xs">{s.l}</div><div className="text-white text-xl font-bold">{s.v}</div></div>)}</div>
    <div className="grid grid-cols-2 gap-4"><div className="bg-slate-800 border border-slate-700 rounded-xl p-5"><h3 className="text-white font-semibold mb-3">Производительность</h3><div className="space-y-2 text-sm">{[['Последний цикл',`${e.last_cycle_ms||0}ms`],['Idempotency Keys',data.idempotencyKeys||0],['Пропущено (Cooldown)',e.skipped_cooldown||0],['Пропущено (Idempotency)',e.skipped_idempotency||0],['Откатов',e.rollbacks||0]].map(([l,v])=><div key={String(l)} className="flex justify-between"><span className="text-slate-400">{l}</span><span className="text-white">{v}</span></div>)}</div></div>
    <div className="bg-slate-800 border border-slate-700 rounded-xl p-5"><h3 className="text-white font-semibold mb-3 flex items-center gap-2"><Zap size={16}/>Последние выполнения</h3><div className="space-y-2 max-h-48 overflow-y-auto">{(data.recentExecutions||[]).slice(0,10).map((ex:any,i:number)=><div key={i} className="flex items-center justify-between bg-slate-700/50 rounded px-3 py-1.5 text-sm"><div className="flex items-center gap-2"><span className={`w-2 h-2 rounded-full ${ex.status==='executed'?'bg-green-500':ex.status==='shadow'?'bg-purple-500':'bg-red-500'}`}/><span className="text-slate-300">{fmt(ex.actionType)}</span></div><span className="text-slate-500 text-xs">{ex.ruleName||''}</span></div>)}{(!data.recentExecutions?.length)&&<div className="text-slate-600 text-center py-3">Нет последних выполнений</div>}</div></div></div>
    {data.roi&&<div className="bg-slate-800 border border-slate-700 rounded-xl p-5" data-testid="roi-summary"><h3 className="text-white font-semibold mb-3">ROI Summary</h3><div className="grid grid-cols-3 gap-3 text-sm"><div className="bg-slate-700/50 rounded-lg p-3"><div className="text-slate-500">Затраты</div><div className="text-white font-medium">${data.roi.totalCost?.toFixed(4)}</div></div><div className="bg-slate-700/50 rounded-lg p-3"><div className="text-slate-500">Выручка</div><div className="text-white font-medium">${data.roi.totalRevenue?.toFixed(2)}</div></div><div className="bg-slate-700/50 rounded-lg p-3"><div className="text-slate-500">Чистый ROI</div><div className={`font-medium ${(data.roi.netROI||0)>=0?'text-green-400':'text-red-400'}`}>{data.roi.netROI?.toFixed(2)}x</div></div></div></div>}
  </div>);
}
