import { useState, useEffect } from 'react';
import { adminAPI } from '../services/api';
import { Shield, AlertTriangle, CheckCircle, Play, RefreshCw } from 'lucide-react';

const fmt = (s: string) => s?.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()) || '';

export default function FailsafePage() {
  const [rules, setRules] = useState<any[]>([]); const [incidents, setIncidents] = useState<any[]>([]); const [testResult, setTestResult] = useState<any>(null); const [loading, setLoading] = useState(true); const [tab, setTab] = useState<'rules'|'incidents'>('rules');
  const load = async () => { try { const [r, i] = await Promise.all([adminAPI.getFailsafeRules(), adminAPI.getFailsafeIncidents()]); setRules(r.data); setIncidents(i.data); } catch {} finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  if (loading) return <div className="p-6 text-slate-400" data-testid="failsafe-loading">Загрузка...</div>;
  return (<div className="p-6 space-y-6" data-testid="failsafe-page"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-white">Failsafe System</h1><p className="text-slate-400 text-sm">Защитные правила и откаты</p></div><div className="flex gap-2"><button onClick={async()=>{try{setTestResult((await adminAPI.testFailsafe()).data);}catch{}}} className="px-4 py-2 bg-amber-600 hover:bg-amber-700 text-white rounded-lg flex items-center gap-2" data-testid="test-failsafe"><Play size={16}/>Тест всех</button><button onClick={load} className="px-3 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg text-slate-300" data-testid="refresh-failsafe"><RefreshCw size={16}/></button></div></div>
    {testResult&&<div className="bg-amber-500/10 border border-amber-500/30 rounded-xl p-4" data-testid="test-results"><h3 className="text-amber-400 font-semibold mb-2">Тест: {testResult.rulesChecked} проверено, {testResult.triggered} сработало</h3><div className="space-y-1">{testResult.results?.map((r:any,i:number)=><div key={i} className="flex items-center gap-2 text-sm"><span className={`w-2 h-2 rounded-full ${r.triggered?'bg-red-500':'bg-green-500'}`}/><span className="text-slate-300">{r.ruleName}</span><span className="text-slate-500">({r.metric} {r.condition})</span></div>)}</div></div>}
    <div className="flex gap-2"><button onClick={()=>setTab('rules')} className={`px-4 py-2 rounded-lg text-sm font-medium ${tab==='rules'?'bg-slate-700 text-white':'text-slate-400 hover:bg-slate-800'}`}>Правила ({rules.length})</button><button onClick={()=>setTab('incidents')} className={`px-4 py-2 rounded-lg text-sm font-medium ${tab==='incidents'?'bg-slate-700 text-white':'text-slate-400 hover:bg-slate-800'}`}>Инциденты ({incidents.length})</button></div>
    {tab==='rules'&&<div className="space-y-3" data-testid="failsafe-rules">{rules.map((r:any)=><div key={r.id} className="bg-slate-800 border border-slate-700 rounded-xl p-4" data-testid={`fs-rule-${r.id}`}><div className="flex items-center justify-between"><div className="flex items-center gap-3"><Shield size={18} className={r.isEnabled?'text-green-400':'text-slate-600'}/><div><div className="text-white font-medium">{r.name}</div><div className="text-sm text-slate-400">{r.metric} {r.condition} &rarr; {fmt(r.rollbackActionType)}</div></div></div><div className="flex items-center gap-3"><span className="text-slate-500 text-sm">{r.incidentsCount||0} инцидентов</span><span className={`px-2 py-0.5 rounded text-xs ${r.isEnabled?'bg-green-500/20 text-green-400':'bg-slate-700 text-slate-500'}`}>{r.isEnabled?'Active':'Off'}</span></div></div></div>)}</div>}
    {tab==='incidents'&&<div className="space-y-3" data-testid="failsafe-incidents">{incidents.map((inc:any)=><div key={inc.id} className="bg-slate-800 border border-slate-700 rounded-xl p-4" data-testid={`incident-${inc.id}`}><div className="flex items-center justify-between"><div className="flex items-center gap-3"><AlertTriangle size={18} className={inc.status==='open'?'text-red-400':'text-green-400'}/><div><div className="text-white font-medium">{inc.ruleName}</div><div className="text-sm text-slate-400">{inc.affectedEntityType} / {fmt(inc.actionTaken)}</div><div className="text-xs text-slate-500">{inc.detectedAt?new Date(inc.detectedAt).toLocaleString('ru-RU'):''}</div></div></div>{inc.status==='open'&&<button onClick={()=>adminAPI.resolveIncident(inc.id).then(load)} className="px-3 py-1 bg-green-600 hover:bg-green-700 text-white rounded text-sm flex items-center gap-1" data-testid={`resolve-${inc.id}`}><CheckCircle size={14}/>Решить</button>}{inc.status==='resolved'&&<span className="text-green-400 text-sm">Решено</span>}</div></div>)}</div>}
  </div>);
}
