import { useState, useEffect } from 'react';
import { adminAPI } from '../services/api';
import { BarChart3, RefreshCw } from 'lucide-react';
export default function FeedbackLoopPage() {
  const [summary, setSummary] = useState<any>(null); const [feedback, setFeedback] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  const load = async () => { try { const [s, f] = await Promise.all([adminAPI.getAutoFeedbackSummary(), adminAPI.getAutoFeedback()]); setSummary(s.data); setFeedback(f.data); } catch {} finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  if (loading) return <div className="p-6 text-slate-400" data-testid="feedback-loading">Загрузка...</div>;
  const impactLabels: Record<string, string> = { positive: 'Позитивный', negative: 'Негативный', neutral: 'Нейтральный' };
  return (<div className="p-6 space-y-6" data-testid="feedback-loop-page"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-white">Feedback Loop</h1><p className="text-slate-400 text-sm">Анализ влияния правил</p></div><button onClick={load} className="px-3 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg text-slate-300" data-testid="refresh-feedback"><RefreshCw size={16}/></button></div>
    {summary&&<><div className="grid grid-cols-4 gap-4" data-testid="feedback-summary"><div className="bg-slate-800 border border-slate-700 rounded-xl p-4"><div className="text-slate-500 text-sm">Всего</div><div className="text-2xl font-bold text-white">{summary.total}</div></div><div className="bg-slate-800 border border-slate-700 rounded-xl p-4"><div className="text-slate-500 text-sm">Позитивных</div><div className="text-2xl font-bold text-green-400">{summary.positive}</div></div><div className="bg-slate-800 border border-slate-700 rounded-xl p-4"><div className="text-slate-500 text-sm">Негативных</div><div className="text-2xl font-bold text-red-400">{summary.negative}</div></div><div className="bg-slate-800 border border-slate-700 rounded-xl p-4"><div className="text-slate-500 text-sm">Средний Score</div><div className="text-2xl font-bold text-white">{summary.avgImpactScore}</div></div></div>
    <div className="bg-slate-800 border border-slate-700 rounded-xl p-5" data-testid="by-rule-table"><h3 className="text-white font-semibold mb-3 flex items-center gap-2"><BarChart3 size={16}/>По правилам</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-slate-500 border-b border-slate-700"><th className="text-left py-2 px-3">Правило</th><th className="text-right py-2 px-3">Всего</th><th className="text-right py-2 px-3">Позитив</th><th className="text-right py-2 px-3">Негатив</th><th className="text-right py-2 px-3">Эффект</th><th className="text-right py-2 px-3">Средн.</th></tr></thead><tbody>{(summary.byRule||[]).map((r:any)=><tr key={r.ruleId} className="border-b border-slate-700/50 text-slate-300"><td className="py-2 px-3 text-white">{r.ruleName}</td><td className="text-right py-2 px-3">{r.total}</td><td className="text-right py-2 px-3 text-green-400">{r.positive}</td><td className="text-right py-2 px-3 text-red-400">{r.negative}</td><td className="text-right py-2 px-3">{r.effectiveness}%</td><td className="text-right py-2 px-3">{r.avgScore}</td></tr>)}</tbody></table></div></div></>}
    <div className="bg-slate-800 border border-slate-700 rounded-xl p-5" data-testid="feedback-history"><h3 className="text-white font-semibold mb-3">Последние Feedback</h3><div className="space-y-2 max-h-80 overflow-y-auto">{feedback.map((f:any)=><div key={f.id} className="flex items-center justify-between bg-slate-700/50 rounded-lg px-3 py-2 text-sm"><div className="flex items-center gap-3"><span className={`w-2 h-2 rounded-full ${f.impactType==='positive'?'bg-green-500':f.impactType==='negative'?'bg-red-500':'bg-amber-500'}`}/><span className="text-slate-300">{impactLabels[f.impactType] || f.impactType}</span></div><span className={`font-medium ${f.impactScore>0?'text-green-400':'text-red-400'}`}>{f.impactScore>0?'+':''}{f.impactScore}</span></div>)}</div></div>
  </div>);
}
