import { useState, useEffect } from 'react';import { adminAPI } from '../services/api';import { DollarSign, TrendingUp, RefreshCw, BarChart3 } from 'lucide-react';

const fmt = (s: string) => s?.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()) || '';

export default function ROITrackingPage(){const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(true);
const load=async()=>{try{setData((await adminAPI.getAutoROISummary()).data);}catch{}finally{setLoading(false);}};
useEffect(()=>{load();const i=setInterval(load,10000);return()=>clearInterval(i);},[]);
if(loading)return<div className="p-6 text-slate-400" data-testid="roi-loading">Загрузка...</div>;if(!data)return<div className="p-6 text-red-400">Ошибка загрузки</div>;
return(<div className="p-6 space-y-6" data-testid="roi-tracking-page"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-white">ROI Tracking</h1><p className="text-slate-400 text-sm">Затраты и влияние на выручку</p></div><button onClick={load} className="px-3 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg text-slate-300" data-testid="refresh-roi"><RefreshCw size={16}/></button></div>
<div className="grid grid-cols-3 gap-4" data-testid="roi-totals"><div className="bg-slate-800 border border-slate-700 rounded-xl p-5"><div className="flex items-center gap-2 text-red-400 mb-2"><DollarSign size={18}/>Общие затраты</div><div className="text-3xl font-bold text-white">${data.totalCost?.toFixed(4)}</div></div><div className="bg-slate-800 border border-slate-700 rounded-xl p-5"><div className="flex items-center gap-2 text-green-400 mb-2"><TrendingUp size={18}/>Влияние на выручку</div><div className="text-3xl font-bold text-white">${data.totalRevenue?.toFixed(2)}</div></div><div className="bg-slate-800 border border-slate-700 rounded-xl p-5"><div className="flex items-center gap-2 text-amber-400 mb-2"><BarChart3 size={18}/>Чистый ROI</div><div className={`text-3xl font-bold ${(data.netROI||0)>=0?'text-green-400':'text-red-400'}`}>{data.netROI?.toFixed(2)}x</div></div></div>
{data.costBreakdown&&<div className="bg-slate-800 border border-slate-700 rounded-xl p-5" data-testid="cost-breakdown"><h3 className="text-white font-semibold mb-3">Разбивка затрат</h3><div className="grid grid-cols-3 gap-3 text-sm"><div className="bg-slate-700/50 rounded-lg p-3"><div className="text-slate-500">Push</div><div className="text-white font-medium">{data.costBreakdown.pushCount} отправлено</div><div className="text-slate-400">${data.costBreakdown.costPerPush?.toFixed(4)}/push</div></div><div className="bg-slate-700/50 rounded-lg p-3"><div className="text-slate-500">Boost</div><div className="text-white font-medium">{data.costBreakdown.incentiveCount} бустов</div><div className="text-slate-400">${data.costBreakdown.costPerIncentive?.toFixed(4)}/boost</div></div><div className="bg-slate-700/50 rounded-lg p-3"><div className="text-slate-500">Surge</div><div className="text-white font-medium">{data.costBreakdown.surgeCount} сёрджей</div><div className="text-slate-400">Среднее: ${data.costBreakdown.avgSurgeImpact}</div></div></div></div>}
<div className="grid grid-cols-2 gap-4"><div className="bg-slate-800 border border-slate-700 rounded-xl p-5" data-testid="roi-by-action"><h3 className="text-white font-semibold mb-3">По действиям</h3><div className="space-y-2">{(data.byAction||[]).map((a:any)=><div key={a.actionType} className="flex items-center justify-between bg-slate-700/50 rounded-lg px-3 py-2 text-sm"><span className="text-slate-300">{fmt(a.actionType)}</span><div className="flex gap-3"><span className="text-red-400">${a.cost?.toFixed(4)}</span><span className="text-green-400">${a.revenue?.toFixed(2)}</span><span className={`font-medium ${a.roi>=0?'text-green-400':'text-red-400'}`}>{a.roi}x</span></div></div>)}</div></div>
<div className="bg-slate-800 border border-slate-700 rounded-xl p-5" data-testid="roi-by-rule"><h3 className="text-white font-semibold mb-3">По правилам</h3><div className="space-y-2">{(data.byRule||[]).map((r:any)=><div key={r.ruleId} className="flex items-center justify-between bg-slate-700/50 rounded-lg px-3 py-2 text-sm"><span className="text-slate-300">{r.ruleName||r.ruleId?.substring(0,8)}</span><span className={`font-medium ${r.roi>=0?'text-green-400':'text-red-400'}`}>{r.roi}x</span></div>)}</div></div></div></div>);}
