import { useState, useEffect } from 'react';import { adminAPI } from '../services/api';import { Globe, RefreshCw, Wifi, WifiOff, ArrowUpDown } from 'lucide-react';
export default function UnifiedStatePage(){const[data,setData]=useState<any>(null);const[health,setHealth]=useState<any>(null);const[loading,setLoading]=useState(true);
const load=async()=>{try{const[u,h]=await Promise.all([adminAPI.getUnifiedState(),adminAPI.getUnifiedStateHealth()]);setData(u.data);setHealth(h.data);}catch{}finally{setLoading(false);}};
useEffect(()=>{load();const i=setInterval(load,5000);return()=>clearInterval(i);},[]);
if(loading)return<div className="p-6 text-slate-400" data-testid="unified-loading">Загрузка...</div>;
const sc:Record<string,string>={surplus:'bg-blue-500',balanced:'bg-green-500',busy:'bg-amber-500',surge:'bg-orange-500',critical:'bg-red-500'};
return(<div className="p-6 space-y-6" data-testid="unified-state-page"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-white">Unified Market State</h1><p className="text-slate-400 text-sm">Единый источник данных о рынке</p></div><div className="flex gap-2"><button onClick={async()=>{try{await adminAPI.syncUnifiedState();load();}catch{}}} className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg flex items-center gap-2" data-testid="sync-btn"><ArrowUpDown size={16}/>Sync</button><button onClick={load} className="px-3 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg text-slate-300" data-testid="refresh-unified"><RefreshCw size={16}/></button></div></div>
{health&&<div className={`rounded-xl p-4 border ${health.health==='healthy'?'bg-green-500/10 border-green-500/30':health.health==='degraded'?'bg-amber-500/10 border-amber-500/30':'bg-red-500/10 border-red-500/30'}`} data-testid="sync-health"><div className="flex items-center gap-2">{health.health==='healthy'?<Wifi size={18} className="text-green-400"/>:<WifiOff size={18} className="text-amber-400"/>}<span className={`font-semibold ${health.health==='healthy'?'text-green-400':'text-amber-400'}`}>Sync: {health.health?.toUpperCase()}</span><span className="text-slate-400 text-sm ml-2">{health.zonesCount} зон</span></div>{health.issues?.length>0&&<div className="mt-2 space-y-1">{health.issues.map((i:any,idx:number)=><div key={idx} className="text-sm text-amber-300">{i.detail}</div>)}</div>}</div>}
{data?.global&&<div className="bg-slate-800 border border-slate-700 rounded-xl p-5" data-testid="global-state"><h3 className="text-white font-semibold mb-4 flex items-center gap-2"><Globe size={18}/>Глобальное состояние</h3><div className="flex items-center gap-3 mb-4"><span className={`px-4 py-1.5 rounded-full text-sm font-medium text-white ${sc[data.global.state]||'bg-slate-600'}`}>{data.global.state?.toUpperCase()}</span><span className="text-slate-400">Engine: <span className={data.engineStatus==='running'?'text-green-400':'text-amber-400'}>{data.engineStatus}</span></span><span className="text-slate-400">Выполнений: {data.totalExecutions||0}</span></div><div className="grid grid-cols-5 gap-3 text-sm">{[{l:'Ratio',v:data.global.ratio},{l:'Спрос',v:data.global.demandCount},{l:'Предл.',v:data.global.supplyCount},{l:'ETA',v:`${data.global.avgEtaMinutes}m`},{l:'Конверсия',v:`${data.global.conversionRate}%`}].map(m=><div key={m.l} className="bg-slate-700/50 rounded-lg p-3"><div className="text-slate-500">{m.l}</div><div className="text-white font-medium">{m.v}</div></div>)}</div></div>}
<div className="bg-slate-800 border border-slate-700 rounded-xl p-5" data-testid="zone-states"><h3 className="text-white font-semibold mb-3">Зоны</h3><div className="grid grid-cols-1 gap-2">{(data?.zones||[]).map((z:any)=><div key={z.scopeId} className="flex items-center justify-between bg-slate-700/50 rounded-lg px-4 py-3"><div className="flex items-center gap-3"><span className={`w-3 h-3 rounded-full ${sc[z.state]||'bg-slate-500'}`}/><span className="text-white font-medium">{z.zoneName||z.scopeId}</span><span className={`px-2 py-0.5 rounded text-xs text-white ${sc[z.state]||'bg-slate-600'}`}>{z.state}</span></div><div className="flex gap-4 text-sm text-slate-400"><span>D:{z.demandCount}</span><span>S:{z.supplyCount}</span><span>R:{z.ratio}</span><span>C:{z.conversionRate}%</span></div></div>)}</div></div></div>);}
